### ISSUE TITLE
The Example Link is broken

### ISSUE THREAD

**Issue by paysheen** [carloslopezolea/E-SFI#1]
Thx for your great work.
I was looking for a simple example and found the link, yet it was seemingly broken and could not find the page.

**Comment by carloslopezolea** [comment]
@paysheen 
The example link has been restored.
If you have any questions, please do not hesitate to contact me.

Regards.

**Comment by paysheen** [comment]
Thanks @carloslopezolea . 
I just found that the model is added to opensees ver3.5. But there I think concrete02 cannot be still used with the model.
So, I used the model you have generously provided in the example file. Unfortunately, whenever the "wipe" command is called using your opensees version the opensees stops going through the rest of the code where some post processing lines are. This does not occur in the official 3.4 or 3.5 version of opensees.
And seemingly this decrepancy happens only when my wall model is E-SFI

**Comment by carloslopezolea** [comment]
@paysheen 
In the official repository of OpenSees the nDMaterial FSAM only works with ConcreteCM (which is less numerically stable than Concrete02). If you want to use the official version, please change Concrete02 to ConcreteCM.
Can you email me an example of your problem? 

Regards!

**Comment by paysheen** [comment]
Thanks, I just sent you the email.
